### ISSUE TITLE
GroundworkCSS

### ISSUE THREAD

**Issue by mhrabiee** [usablica/front-end-frameworks#144]
This project ([Groundwork 2](http://groundworkcss.github.io)) is not dead (yet)  and lots of WordPress theme developer using it. But i was removed from the list due to PR #139. (Though it is still on the compare.html in GitHub Pages).
Maybe it's a good idea to bring it back to the list.

Thanks.

**Comment by diomed** [comment]
it's not in active development, so it's as good as dead.

**Comment by mhrabiee** [comment]
So this issue can be safely closed. 😄
